#!/usr/bin/env python3
"""Rebuild the mod's environment files from the vanilla ones with a fog preset.

Usage: tools/apply_preset.py <preset>

The five environment files this mod overrides are identical in vanilla as far as
fog goes, so a preset is just a set of values written into all of them. Rebuilding
from the game install rather than editing in place also means the mod picks up any
other change Paradox makes to these files.

Fog maths, from jomini_fog.fxh:

    Diff       = CameraPosition - WorldSpacePos
    HorizFac   = 1 - abs( normalize( Diff ).y )
    Ramp       = min( ( |Diff|^2 - fog_begin^2 ) / ( fog_end^2 - fog_begin^2 ), fog_max )
    FogFactor  = saturate( Ramp * HorizFac ) * zoom fade * ( 1 - height fade ) * noise
    FogColour  = fog_color + smoothstep( CamX + rel_begin, CamX - rel_end, WorldX ) * relative_fog_color
    Pixel      = lerp( Pixel, FogColour, FogFactor )

HorizFac is the ultrawide problem: looking down at the centre of the screen the
vector to the terrain is mostly vertical and the factor is near zero, while towards
the left and right edges it becomes nearly horizontal and the factor approaches one.
The wider the screen, the more of it sits in the haze - and fog_end / rel_begin /
rel_end are all tuned for how far a 16:9 screen reaches.
"""
import pathlib
import sys

VANILLA = pathlib.Path.home() / ".local/share/Steam/steamapps/common/Crusader Kings III/game/gfx/map/environment"
OUT = pathlib.Path(__file__).resolve().parent.parent / "gfx/map/environment"
FILES = ["environment", "environment_top_left", "environment_bottom_left",
         "environment_ce2", "environment_compromise"]

PRESETS = {
    # exactly vanilla - for A/B against the mod being disabled
    "vanilla": dict(fog_max="0.2", fog_end="500",
                    rel_color="{ 0.6 0.2 -0.2 }", rel_begin="100.0", rel_end="400.0"),
    # distances scaled by 32:9 / 16:9 = 2, so a given screen position gets the
    # haze a 16:9 player sees there. Keeps the warm tint.
    "scaled": dict(fog_max="0.2", fog_end="1000",
                   rel_color="{ 0.6 0.2 -0.2 }", rel_begin="200.0", rel_end="800.0"),
    # scaled, and the asymmetric warm tint dropped: haze stays the fog colour
    "neutral": dict(fog_max="0.2", fog_end="1000",
                    rel_color="{ 0 0 0 }", rel_begin="200.0", rel_end="800.0"),
    # as neutral, with the strength cap cut from 20% to 8%
    "soft": dict(fog_max="0.08", fog_end="1000",
                 rel_color="{ 0 0 0 }", rel_begin="200.0", rel_end="800.0"),
    # no distance fog at all - fog_max 0 zeroes the ramp
    "off": dict(fog_max="0.0", fog_end="500",
                rel_color="{ 0 0 0 }", rel_begin="100.0", rel_end="400.0"),
}

REPLACE = {
    "fog_max": "fog_max = {fog_max}",
    "fog_end": "fog_end = {fog_end}",
    "relative_fog_color": "relative_fog_color = {rel_color}",
    "relative_fog_begin": "relative_fog_begin = {rel_begin}",
    "relative_fog_end": "relative_fog_end = {rel_end}",
}

def main():
    if len(sys.argv) != 2 or sys.argv[1] not in PRESETS:
        print(f"Usage: {sys.argv[0]} <{' | '.join(PRESETS)}>", file=sys.stderr)
        return 1
    name = sys.argv[1]
    values = PRESETS[name]
    if not VANILLA.is_dir():
        print(f"Vanilla environment files not found at {VANILLA}", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    for stem in FILES:
        text = (VANILLA / f"{stem}.txt").read_text(encoding="utf-8-sig")
        out = []
        for line in text.split("\n"):
            key = line.split("=")[0].strip()
            if key in REPLACE:
                out.append(REPLACE[key].format(**values))
            else:
                out.append(line)
        header = f"# Ultrawide Fog Tint Fix - preset \"{name}\", generated by tools/apply_preset.py\n"
        (OUT / f"{stem}.txt").write_text(header + "\n".join(out), encoding="utf-8")
    print(f"preset '{name}' written to {OUT}")
    for k, v in values.items():
        print(f"   {k:10} {v}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
